(* ::Package:: *)

(* ::Title:: *)
(*QMRITools ElastixTools*)


(* ::Subtitle:: *)
(*Written by: Martijn Froeling, PhD*)
(*m.froeling@gmail.com*)


(* ::Section:: *)
(*Begin Package*)


BeginPackage["QMRITools`ElastixTools`", Join[{"Developer`"}, Complement[QMRITools`$Contexts, {"QMRITools`ElastixTools`"}]]];


(* ::Section:: *)
(*Usage Notes*)


(* ::Subsection::Closed:: *)
(*Functions*)


ClearQMRIToolsTemp::usage =
"ClearQMRIToolsTemp[] clears the temporary directory used by QMRITools for registration."

RegisterData::usage =
"RegisterData[data] registers the data series. If data is 3D it performs multiple 2D registration, if data is 4D it performs multiple 3D registration.
The input data can be in the forms: data, {data, vox}, {data, mask} or {data, mask, vox}.

RegisterData[target, moving] registers the moving data to the target data. target can be 2D or 3D. moving can be the same of one dimension higher than the target.
The inputs target and moving can be in the forms: data, {data, vox}, {data, mask} or {data, mask, vox}.

Output is the registered data with the dimensions of the moving data. 
If OutputTransformation is True it also outputs the translation, rotation scale and skew of all images or volumes.

RegisterData[] is based on DOI: 10.1109/TMI.2009.2035616 and 10.3389/fninf.2013.00050."

RegisterDataSplit::usage = 
"RegisterDataSplit[target, moving] is identical to RegisterData data however left and right side of the data are registered separately.

Splitting the data is done using the function CutData and merged wit Stich data.
Output is the registered data."


TransformData::usage = 
"TransformData[{data,vox}] deforms the data according to the last output of register data.
The directory should be the TempDirectory were the registration is stored. DeleteTempDirectory should be False."

ReadTransformParameters::usage = 
"ReadTransformParameters[directory] reads the transformation parameters generated by RegisterData. The directory should be the TempDirectory were the registration is stored. DeleteTempDirectory should be False.

Output is the affine transformation vector per volume."


RegisterDataTransform::usage = 
"RegisterDataTransform[target, moving, {moving2nd, vox}] performs the registration exactly as RegisterData. target and moving are the inputs for RegisterData, which can be {data,mask,vox}.
After the registration is done the moving2nd data is deformed according to the output of the registration of moving.

moving2nd can have the same dimensions of moving or one dimension higher (e.g. 3D and 3D or 3D and 4D). 

Output is {registered moving, deformed moving2nd}."

RegisterDataTransformSplit::usage = 
"RegisterDataTransformSplit[target, moving, {moving2nd, vox}] is identical to RegisterDataTransform with the same functionality as RegisterDataSplit.
This means the data is split in two using the function CutData and merged wit Stich data.

Output is {registered moving, deformed moving2nd}."


RegisterDiffusionData::usage =
"RegisterDiffusionData[{dtiData, vox}] registers a diffusion dataset. dtiData should be 4D {slice, diff, x, y}. vox is the voxel size of the data.
RegisterDiffusionData[{dtiData, dtiMask, vox}] registers the data series using the given voxel size only using data within the mask.
RegisterDiffusionData[{dtiData ,vox}, {anatData, voxAnat}] registers a diffusion dataset. The diffusion data is also registered to the anatData.
RegisterDiffusionData[{dtiData, dtiMask, vox}, {anatData, voxAnat}] registers the data series using the given voxel size only using data within the mask.
RegisterDiffusionData[{dtiData,vox}, {anatData, anatMast, voxAnat}] registers the data series using the given voxel size only using data within the mask.
RegisterDiffusionData[{dtiData, dtiMask, vox}, {anatData, anatMast, voxAnat}] registers the data series using the given voxel size only using data within the mask.

Output is the registered dtiData and, if anatData is given, the registered dtiData in anatomical space. If OutputTransformation is True it also outputs the translation, rotation scale and skew of all images or volumes."

RegisterDiffusionDataSplit::usage = 
"RegisterDiffusionDataSplit[dtiData, vox] is identical to Register diffusion data however left and right side of the data are registered separately.
RegisterDiffusionDataSplit[{dtiData, vox}, {anatData, voxAnat}] is identical to Register diffusion data however left and right side of the data are registered separately.
RegisterDiffusionDataSplit[{dtiData, dtiMask, vox}, {anatData, anatMast, voxAnat}] is identical to Register diffusion data however left and right side of the data are registered separately.

Splitting the data is done using the function CutData and merged wit Stich data.
Output is the registered data."


RegisterTensorData::usage =
"RegisterTensorData[target, moving] registers the moving tensor to the target tensor. After registration the tensor is reorientated appropriately. 
The inputs target and moving can be in the forms: tensor, {tensor, vox}, {tensor, mask} or {tensor, mask, vox}.
RegisterTensorData[target, moving, tensor] registers the moving data to the target data and applies the deformation to the tensor. 
The inputs target and moving can be in the form: data, {data, vox}, {data, mask} or {data, mask, vox}.
The input tensor can be in the form: tensor or {tensor, vox}.

only \"rigid\", \"affine\" and \"bspline\" can be used as MetReg."


RegisterCardiacData::usage =
"RegisterCardiacData[data] registers the data using a 2D algorithm. data can be 3D or 4D.
RegisterCardiacData[{data,vox}] registers the data series using the given voxel size.
RegisterCardiacData[{data,mask}] registers the data series only using data within the mask.
RegisterCardiacData[{data,mask,vox}] registers the data series using the given voxel size only using data within the mask.

Output is the registered data."


$lastElastixTemp::usage = "$lastElastixTemp is the last temporary directory used by Elastix.";

$debugElastix::usage = "$debugElastix is a debug flag for Elastix functionality.";


(* ::Subsection::Closed:: *)
(*Options*)


Iterations::usage =
"Iterations is an options for RegisterData, RegisterDiffusionData, and RegisterDataTransform. 
It specifies the number of iterations used by the registration functions."

Resolutions::usage =
"Resolutions is an options for RegisterData, RegisterDiffusionData, and RegisterDataTransform. 
It specifies the number of scale space resolutions used by the registration functions."

HistogramBins::usage =
"HistogramBins is an options for RegisterData, RegisterDiffusionData, and RegisterDataTransform. 
It specifies the number of bins of the joined histogram used by the registration functions."

NumberSamples::usage =
"NumberSamples is an options for RegisterData, RegisterDiffusionData, and RegisterDataTransform. 
It specifies the number of random samples that are taken each iteration used by the registration functions."

OutputImage::usage =
"OutputImage is an options for RegisterData, RegisterDiffusionData, and RegisterDataTransform. 
It specifies if the result image should be written in the TempDirectory as nii file."

InterpolationOrderReg::usage =
"InterpolationOrderReg is an options for RegisterData, RegisterDiffusionData, and RegisterDataTransform. 
It specifies the interpolation order used in the registration functions."

MethodReg::usage = 
"MethodReg is an options for RegisterData, RegisterDiffusionData, RegisterCardiacData and RegisterDataTransform. 
It specifies which registration method to use. 
Methods can be be \"translation\", \"rigid\", \"affine\", \"bspline\", \"rigidDTI\", \"affineDTI\", \"PCAtranslation\", \"PCArigid\", \"PCAaffine\", or \"PCAbspline\"."

BsplineSpacing::usage =
"BsplineSpacing is an options for RegisterData, RegisterDiffusionData, RegisterCardiacData and RegisterDataTransform. 
It specifies the spacing of the bspline if the method is \"bspline\"."

TempDirectory::usage = 
"TempDirectory is an options for RegisterData, RegisterDiffusionData, RegisterCardiacData and RegisterDataTransform. 
It specifies the temporary directory used to perform and output the registration."

DeleteTempDirectory::usage =
"DeleteTempDirectory an options for RegisterData, RegisterDiffusionData, RegisterCardiacData and RegisterDataTransform. 
It specifies if the temp directory should be deleted after the registration is finished."

PrintTempDirectory::usage = 
"PrintTempDirectory is an options for RegisterData, RegisterDiffusionData, RegisterCardiacData and RegisterDataTransform. 
It specifies if the location of the temp directory should be displayed."

RegistrationTarget::usage = 
"RegistrationTarget is an option for RegisterDiffusionData and RegisterCardiacData. Specifies which target to uses for registration if using \"rigid\", \"affine\" or \"bspline\" as MethodReg.
If the MethodReg is \"PCA\" based it does not need a target and this options does nothing. 
Values can be \"First\", \"Mean\" or \"Median\"."

BsplineDirections::usage = 
"BsplineDirections is an option for RegisterData ad RegisterDiffusionData. 
It gives the direction in which the bspline are allowed to move when registering diffusion data to anatomical space."

AffineDirections::usage = 
"AffineDirections is an option for RegisterData ad RegisterDiffusionData. 
It gives the directions in which data can be moved when registering diffusion data to anatomical space."

OutputTransformation::usage =
"OutputTransformation is an option for RegisterData ad RegisterDiffusionData.
It specifies if the transformation parameters (translation, rotation, scale and skew) should be given as output in the registration functions."

IterationsA::usage = 
"IterationsA is an option for RegisterDiffusionData. 
It specifies the number of iterations used when registering diffusion data to anatomical space."

ResolutionsA::usage =
"ResolutionsA is an option for RegisterDiffusionData.
It specifies the number of scale space resolutions used when registering diffusion data to anatomical space."

HistogramBinsA::usage =
"HistogramBinsA is an option for RegisterDiffusionData.
It specifies the number of bins of the joined histogram used when registering diffusion data to anatomical space."

NumberSamplesA::usage =
"NumberSamplesA is an option for RegisterDiffusionData.
It specifies the number of random samples that are taken each iteration when registering diffusion data to anatomical space."

InterpolationOrderRegA::usage =
"InterpolationOrderRegA is an option for RegisterDiffusionData.
It specifies the interpolation order used in the registration functions when registering diffusion data to anatomical space."

MethodRegA::usage =
"MethodRegA is an option for RegisterDiffusionData.
It specifies which registration method to use when registering diffusion data to anatomical space. Methods can be be \"rigid\",\"affine\" or \"bspline\"."

ShowMetric::usage=
"ShowMetric is an option for RegisterData. If set to True it will print a plot of the Metric."

UseGPU::usage = 
"UseGPU is an option for RegisterData. The value is {bool, gpu} where bool is True or False, and gpu is the gpu ID which is an integer or Automatic."

PCAComponents::usage = 
"PCAComponents is an option for RegisterData. It specifies how many PCA components are used if method is set to \"PCA\"."

FindTransform::usage = 
"FindTransform is an option for TransformData and RegisterTransformData. It specifies where to find the transform file."

ImportDeformation::usage = 
"ImportDeformation is an option for TransformData and RegisterTransformData. It specifies if the transformation field which is generated by 
Transformix should be imported along side the transformation result."

SplitMethod::usage = 
"SplitMethod is an option for RegisterDataSplit and RegisterDataTransformSplit. values can be \"mean\", \"moving\", \"target\"."

TransformMethod::usage = 
"TransformMethod is an option for RegisterDataSplit and RegisterDataTransformSplit. values can be \"Data\", \"Mask\", \"Segmentation\". 
If set to \"Mask\" a binary mask is expected as the second moving input.
If set to \"Segmentation\" a multi label segmentation is expected as the second moving input.
Uses SplitSegmentations internally then."

(* ::Subsection::Closed:: *)
(*Error Messages*)


RegisterData::inp="Invalid input for registration function." 

RegisterData::vol="The `1`D datasets should have 2 or more volumes, it has `2` volumes."

RegisterData::dim="Datasets should both be 2D or 3D, or 2D and 3D, or 3D and 4D, current datasets are `1`D and `2`D."

RegisterData::dims="Dataset should be 3D or 4D, current dataset is `1`D."

RegisterData::vox="voxel size should be {z,x,y} and numeric, current sizes are `1` and `2`."

RegisterData::voxS="voxel size should be {z,x,y} and numeric, current size is `1`."

RegisterData::met="MethodReg should be \"translation\", \"rigid\", \"similarity\", \"affine\", \"bspline\", \"rigidDTI\", \"affineDTI\", 
\"PCAtranslation\", \"PCArigid\", \"PCAaffine\", or \"PCAbspline\", \"rigidMulti\", \"affineMulti\", 
\"bsplineMulti\", current method is `1`."

RegisterData::metC="If the MethodReg is \"PCAxx\" no target can be given. If the method is \"xxxMulti\" a target should be given."

RegisterData::cyc="If any MethodReg is \"PCAxx\" all should be \"PCAxx\"."

RegisterData::mult="If any MethodReg is \"xxxMulti\" all should be \"xxxMulti\"."

RegisterData::mask="The mask dimensions `1` should be equal to the data dimensions `2`."

RegisterData::dir="Temporary directory not created."

RegisterData::elastix="Elastix not found, check if QMRITools is installed in the $BaseDirectory or $UserBaseDirectory."

RegisterData::par="`1` should be a number or a list of numbers with length `2`."

RegisterData::fatal="Fatal error encountered."


(* ::Section:: *)
(*Functions*)

Begin["`Private`"]


debugElastix[x___] := If[$debugElastix, Print[x]];


(* ::Subsection::Closed:: *)
(*Definitions*)


$lastElastixTemp = "";
$debugElastix = False;


operatingSystem = $OperatingSystem;


(* ::Subsection:: *)
(*Support Functions*)


(* ::Subsubsection::Closed:: *)
(*ClearQMRIToolsTemp*)


SyntaxInformation[ClearQMRIToolsTemp] = {"ArgumentsPattern"->{}};

ClearQMRIToolsTemp[] := DeleteDirectory[FileNames["*QMRIToolsReg*", $TemporaryDirectory], DeleteContents -> True]


(* ::Subsubsection::Closed:: *)
(*ParString*)


ParString[
	{iterations_, resolutions_, bins_, samples_, intOrder_}, 
	{type_, output_}, 
	{{dTar_, n_}, grid_, derScaleB_, derScaleA_, eig_}, 
	{openCL_, gpu_}
]:=Block[
	{pca, mul},
	pca = (type === "PCAtranslation" || type === "PCArigid" || type === "PCAaffine" || type==="PCAbspline");
	mul = (type === "rigidMulti" || type === "affineMulti" || type === "bsplineMulti");

"// ***************************************************************
// ** "<>type<>" **

// ** Generated using QMRITools by M.Froeling **

// ** fixed general settings **
// ***************************************************************
(FixedInternalImagePixelType \"float\")
(MovingInternalImagePixelType \"float\")
(UseDirectionCosines \"true\")

(DefaultPixelValue 0)
(WriteTransformParametersEachIteration \"false\")
(ResultImageFormat \"nii.gz\")
(ResultImagePixelType \"float\")

(ErodeMask \"false\")
(ErodeMovingMask \"false\")
(ErodeFixedMask \"false\")

(Registration "<>If[!mul, "\"MultiResolutionRegistration\"", "\"MultiMetricMultiResolutionRegistration\""]<>")

(ImageSampler "<>StringRep["\"RandomCoordinate\"", n]<>")
(CheckNumberOfSamples \"true\")
(NewSamplesEveryIteration \"true\")
(MaximumNumberOfSamplingAttempts 5)

(HowToCombineTransforms \"Compose\")

(Optimizer \"AdaptiveStochasticGradientDescent\")
(ASGDParameterEstimationMethod \"Original\")
(AutomaticParameterEstimation \"true\")
(AutomaticTransformInitialization \"true\")
(AutomaticScalesEstimation \"true\")

"<>If[openCL,
(*check to uses openCL needs custom compile of elastix*)
"(OpenCLDeviceID \""<>ToString[gpu]<>"\")
(Resampler \"OpenCLResampler\")
(OpenCLResamplerUseOpenCL \"true\")
(FixedImagePyramid "<>StringRep["\"OpenCLFixedGenericImagePyramid\"", n]<>")
(OpenCLFixedGenericImagePyramidUseOpenCL \"true\")
(MovingImagePyramid "<>StringRep["\"OpenCLMovingGenericImagePyramid\"", n]<>")
(OpenCLMovingGenericImagePyramidUseOpenCL \"true\")"
,

"(Resampler \"DefaultResampler\")
(FixedImagePyramid "<>StringRep["\"FixedGenericImagePyramid\"", n]<>")
(MovingImagePyramid "<>StringRep["\"MovingGenericImagePyramid\"", n]<>")"
]<>"
// ***************************************************************


// ** Metric settings **
// ***************************************************************
"<>Which[(*if PCA uses stack transform*)
(*PCA based methods*)
pca,
"(Metric \"PCAMetric2\")
(NumEigenValues "<>ToString[eig]<>")
(SubtractMean \"true\")

(Interpolator \"ReducedDimensionBSplineInterpolator\")
(ResampleInterpolator \"FinalReducedDimensionBSplineInterpolator\")",
True,
(*Non PCA based methods*)
If[StringContainsQ[type, "Mask"],
"(Metric "<>StringRep["\"AdvancedMeanSquares\"", n]<>")",
"(Metric "<>StringRep["\"AdvancedMattesMutualInformation\"", n]<>")"
]<>"
(Interpolator "<>StringRep["\"BSplineInterpolator\"", n]<>")
(ResampleInterpolator \"FinalBSplineInterpolator\")"
]<>"
// ***************************************************************


// ** setting allowed by QMRITools **
// ***************************************************************
(WriteResultImage \""<>output<>"\")

(NumberOfResolutions "<>ToString[resolutions]<>")
"<>Which[(*if multi resolution PCA imagePyramidSchedule has to be defined*)
pca,
"(ImagePyramidSchedule "<>SchedulePar[resolutions, dTar]<>")",
True,""
]<>"
(BSplineInterpolationOrder "<>ToString[Clip[intOrder,{1,3},{1,3}]]<>")
(FinalBSplineInterpolationOrder "<>ToString[intOrder]<>")

(NumberOfHistogramBins "<>ToString[bins]<>")
(MaximumNumberOfIterations "<>ToString[iterations]<>")

(NumberOfSpatialSamples "<>ToString[samples]<>")
// ***************************************************************


// ** Transform type specific settings **
// ***************************************************************
"<>Switch[type, (*switch between registration types*)
(*normal or multi methods*)	
"translation" | "translationMask",
"(Transform \"TranslationTransform\")",
"rigid" | "rigidMulti" | "rigidMask",
"(Transform \"EulerTransform\")",
"similarity" | "similarityMask",
"(Transform \"SimilarityTransform\")",
"affine" | "affineMulti" | "affineMask",
"(Transform \"AffineTransform\")
(MovingImageDerivativeScales "<>DerivativePar[N@Clip[derScaleA], dTar]<>")",
"bspline" | "bsplineMulti" | "bsplineMask",
"(Transform \"RecursiveBSplineTransform\")
(FinalGridSpacingInPhysicalUnits "<>DerivativePar[N@Round[grid], dTar]<>")
(MovingImageDerivativeScales "<>DerivativePar[N@Clip[derScaleB], dTar]<>")",

(*DTI methods*)
"rigidDTI",
"(Transform \"AffineDTITransform\")
(Scales -1.0 -1.0 -1.0  3.0e+38  3.0e+38  3.0e+38  3.0e+38  3.0e+38  3.0e+38 -1.0 -1.0 -1.0)",
"affineDTI",
"(Transform \"AffineDTITransform\")
(Scales -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1)
(MovingImageDerivativeScales "<>DerivativePar[N@Clip[derScaleA], dTar]<>")",

(*PCA methods*)
"PCAtranslation",
"(Transform \"TranslationStackTransform\")
(MovingImageDerivativeScales "<>DerivativePar[{1.,1.,1.}, dTar-1, "0.0"]<>")",
"PCArigid",
"(Transform \"EulerStackTransform\")
(MovingImageDerivativeScales "<>DerivativePar[{1.,1.,1.}, dTar-1, "0.0"]<>")",
"PCAaffine",
"(Transform \"AffineLogStackTransform\")
(MovingImageDerivativeScales "<>DerivativePar[{1.,1.,1.}, dTar-1, "0.0"]<>")",
"PCAbspline",
"(Transform \"BSplineStackTransform\")
(FinalGridSpacingInPhysicalUnits "<>DerivativePar[Round[grid], dTar-1]<>")
(MovingImageDerivativeScales "<>DerivativePar[N@Clip[derScaleB], dTar-1, "0.0"]<>")"
]<>"
// ***************************************************************

//****************** end of file ***************
"
]

StringRep[st_, n_] := StringJoin@Riffle[ConstantArray[st, n], " "]

ListToString[list_, add_: ""] := StringTrim[StringJoin[Riffle[ToString /@ list, " "]] <> " " <> add]

SchedulePar[res_, dTar_] := ListToString[ListToString[2.^ConstantArray[#, dTar - 1], "0.0"] & /@ Reverse[Range[res] - 1]]

DerivativePar[par_, dTar_, add_: ""] := ListToString[Reverse[par[[-dTar ;;]]], add]


(* ::Subsubsection::Closed:: *)
(*ElastixCommand*)


ElastixCommand[elastixExe_, tempdir_, parFile_, folders_, files_, mask_]:=ElastixCommand[elastixExe, tempdir, parFile, folders, files, mask, 1]

ElastixCommand[elastixExe_, tempdir_, parFile_, {inputFolderI_, moveFolderI_, outFolderI_}, {fixedI_, movingI_, out_}, {maskFI_, maskMI_}, n_]:=Block[{
		quote, cp, num, maskF, maskM, command, resultOut, fileInOut, output, elastix, outFile,
		inputFolder, outFolder, moveFolder, parFiles, copy, maskFFile, maskMFile, elastixFol, fixedFile, moveFile
	},

	(*operating specific settings *)
	quote = Switch[operatingSystem,"Windows","\"",_,"'"];
	cp = Switch[operatingSystem,"Windows","@ copy ",_,"cp "];

	elastix = quote<>elastixExe<>quote;
	elastixFol = DirectoryName[elastixExe, 2];

	elastix = Switch[operatingSystem, 
		"Windows", 
		"@ "<>elastix,
		"MacOSX", 
		"export PATH="<>elastixFol<>"bin:$PATH\nexport DYLD_LIBRARY_PATH="<>elastixFol<>"lib:$DYLD_LIBRARY_PATH\n"<>elastix,
		"Unix",
		"export PATH="<>elastixFol<>"bin:$PATH\nexport LD_LIBRARY_PATH="<>elastixFol<>"lib:$LD_LIBRARY_PATH\n"<>elastix
	];

	(*in and output folders*)
	inputFolder = FileNameJoin[{tempdir, inputFolderI}];
	moveFolder = FileNameJoin[{tempdir, moveFolderI}];
	outFolder = FileNameJoin[{tempdir, outFolderI}];
	outFile = FileNameJoin[{outFolder, out}];

	(*moving and fixed files*)
	fixedFile = MakeElastixFiles["-f", fixedI, inputFolder, quote, n];
	moveFile = MakeElastixFiles["-m", movingI, moveFolder, quote, n];

	(*mask files*)	
	maskF = If[FileExtension[maskFI] == "nii", maskFI<>".gz", maskFI];
	maskM = If[FileExtension[maskMI] == "nii", maskMI<>".gz", maskMI];
	maskFFile = If[maskF==="", "", " -fMask "<>quote<>FileNameJoin[{tempdir,maskF}]<>quote];
	maskMFile = If[maskM==="", "", " -mMask "<>quote<>FileNameJoin[{tempdir,maskM}]<>quote];

	(*par file string*)
	parFiles = StringJoin[" -p "<>quote<>FileNameJoin[{tempdir,#}]<>quote &/@parFile];

	(*output*)
	outFolder = " -out "<>quote<>outFolder<>quote;
	output = " > "<>quote<>FileNameJoin[{moveFolder,"output.txt"}]<>quote;

	(*copy string*)
	copy = If[out=="", 
		"", 
		(*how many par files*)
		num=ToString[Length[parFile]-1];
		resultOut = quote<>FileNameJoin[{tempdir, outFolderI, "result."<>num<>".nii.gz"}]<>quote;
		fileInOut = quote<>FileNameJoin[{tempdir, outFolderI, out}]<>quote;
		cp<>resultOut<>" "<>fileInOut
	];

	command = elastix<>fixedFile<>moveFile<>outFolder<>maskFFile<>maskMFile<>parFiles<>output<>" \n"<>copy<>" \n"<>"exit \n";

	{command, outFile}	
]


MakeElastixFiles[pre_, fileI_, fol_, q_, n_]:=Block[{fixed, index, file},
	StringJoin[(
		index = StringPadInteger["-",#];
		file = If[n===1, fileI, fileI[index]];
		fixed = If[FileExtension[file] == "nii", file<>".gz", file];
		" "<>pre<>If[n===1, "", ToString[#-1]]<>" "<>q<>FileNameJoin[{fol, fixed}]<>q
	)&/@Range[n]]
]


(* ::Subsubsection::Closed:: *)
(*TransformixCommand*)


TransformixCommand[tempDir_, ind_] := Block[{
	trans, quote, cp, transformix, transFol, transFile, movFile, output, outFolder, volDirs, copy
	},

	trans = GetAssetLocation["Transformix"];

	(*operating specific settings *)
	quote = Switch[operatingSystem, "Windows", "\"", _, "'"];
	cp = Switch[operatingSystem, "Windows","@ copy ", _, "cp "];

	(*transformix command*)
	transformix = quote<>trans<>quote;
	transFol = DirectoryName[trans, 2];
	transformix = Switch[operatingSystem, 
		"Windows", 
		"@ "<>transformix,
		"MacOSX", 
		"export PATH="<>transFol<>"bin:$PATH\nexport DYLD_LIBRARY_PATH="<>transFol<>"lib:$DYLD_LIBRARY_PATH\n"<>transformix,
		"Unix",
		"export PATH="<>transFol<>"bin:$PATH\nexport LD_LIBRARY_PATH="<>transFol<>"lib:$LD_LIBRARY_PATH\n"<>transformix
	];

	(*make trans file*)
	If[ind,
		(*individual trans file*)
		(*files*)
		transFile = " -tp "<>quote<>TransFileT[tempDir]<>quote;
		movFile = " -in " <>quote<>MovFileT[tempDir]<>quote;

		(*outputs*)
		outFolder = " -def all -out "<>quote<>tempDir<>quote;
		output = " > "<>quote<>FileNameJoin[{tempDir, "output.txt"}]<>quote;

		(*command*)
		transformix <> movFile <> outFolder <> transFile <> output<>" \n exit \n"
		,
		(*range of trans files*)
		volDirs = FileNames["vol*", tempDir, 1];
		(
			(*files*)
			transFile = " -tp "<>quote<>TransFileF[#]<>quote;
			movFile = " -in " <>quote<>MovFileF[#]<>quote;

			(*outputs*)
			outFolder = " -def all -out "<>quote<>#<>quote;
			output = " > "<>quote<>FileNameJoin[{#, "output.txt"}]<>quote;

			(*copy*)
			copy = cp<>quote<>FileNameJoin[{#, "result.nii.gz"}]<>quote<>" "<>quote<>FileNameJoin[{#, "resultA-3D.nii.gz"}]<>quote;

			(*command*)
			transformix <> movFile <> outFolder <> transFile <> output<>" \n"<>copy<>" \n"
		)&/@volDirs
	]
]


MovFileF[fol_] := First[FileNames["moving*", fol]];
	
TransFileF[fol_] := Last[SortBy[FileNames["FinalTransform*", fol], FileDate[#, "Modification"] &]];

MovFileT[fol_] := First[FileNames["trans*", fol]];

TransFileT[fol_] := Last[SortBy[FileNames["TransformParameters*", DirectoryName[fol]], FileDate[#, "Modification"] &]];


(* ::Subsubsection::Closed:: *)
(*ConcatenateTransformFiles*)


ConcatenateTransformFiles[files_, outDir_] := Block[{len, filesI, transFile, f, p},
	(*import the transform files*)
	len = Range[Length[files]];
	filesI = Import[#, "Lines"] & /@ files;

	(*concatenate the transform files*)
	(
		f = filesI[[#]];
		transFile = If[# == 1, "NoInitialTransform", outDir <> $PathnameSeparator <> "FinalTransform." <> ToString[# - 2] <> ".txt"];
		p = Position[Boole[StringContainsQ[#, "InitialTransformParameterFileName"] & /@ f], 1][[1, 1]];

		f[[p]] = "(InitialTransformParameterFileName \"" <> transFile <> "\")";
		Export[outDir <> $PathnameSeparator <> "FinalTransform." <> ToString[# - 1] <> ".txt", f];
	) & /@ len;
]


(* ::Subsubsection::Closed:: *)
(*RunCommands*)


RunCommands[cmds_] := RunCommands[cmds, "E"]

RunCommands[cmds_, f_] := Block[{list},
	list = Flatten[{cmds}];

	debugElastix["Command list"<>If[Length[list]>1," 1/"<>ToString[Length[list]],""]<>":\n" <> First[list]];
	Export[
		FileNameJoin[{$lastElastixTemp, Switch[f,"E", "elastix", "T", "transformix"]<>"_commands.txt"}],
		StringRiffle[list, "\n"], "Text"
	];
	
	If[Length[list] > 4, ParallelMap, Map][RunProcess[$SystemShell, "StandardOutput", #] &, list]
]


(* ::Subsubsection::Closed:: *)
(*SplitRegInput*)


SplitRegInput[input_] := Which[
	ArrayQ[input],(*Only data*)
	{input, {1}, {1, 1, 1}},
	Length[input] == 2 && ArrayQ[input[[1]]] && (VectorQ[input[[2]]] && Length[input[[2]]] === 3),(*data and vox*)
	{input[[1]], {1}, input[[2]]},
	Length[input] == 2 && ArrayQ[input[[1]]] && (ArrayQ[input[[2]]] || input[[2]] === {1}),(*data and mask*)
	{input[[1]], input[[2]], {1, 1, 1}},
	Length[input] == 3 && ArrayQ[input[[1]]] && (ArrayQ[input[[2]]] || input[[2]] === {1}) && (VectorQ[input[[3]]] && Length[input[[3]]] === 3),(*full input*)
	input,
	True,
	$Failed
]


(* ::Subsection:: *)
(*RegisterData/Split*)


CreateTempDirectory[tempDirI_] := CreateTempDirectory[tempDirI, False, False]
CreateTempDirectory[tempDirI_, print_] := CreateTempDirectory[tempDirI, print, False]
CreateTempDirectory[tempDirI_, print_, make_] := Block[{tempDir, add, str},
	(*define temp directory folder name*)
	{tempDir, add} = If[ListQ[tempDirI], tempDirI, {tempDirI, ""}];
	str = RandomString[6];

	tempDir = (If[StringQ[tempDir], tempDir, "Default"] /. {"Default" -> $TemporaryDirectory});
	tempDir = If[StringContainsQ[Last[FileNameSplit[tempDir]], "QMRIToolsReg"] || Last[FileNameSplit[tempDir]] === "anat",
		FileNameJoin[{tempDir, add}],
		FileNameJoin[{tempDir, "QMRIToolsReg-" <> str, add}]
	];

	(*delete and create if needed*)
	If[make, If[DirectoryQ[tempDir], DeleteDirectory[tempDir, DeleteContents -> True]]; CreateDirectory[tempDir]];
	tempDir = If[! DirectoryQ[tempDir], CreateDirectory[tempDir], tempDir];
	tempDir = AbsoluteFileName[tempDir];

	(*print if needed*)
	If[print, Print["using as temp directory: ", Hyperlink[tempDir, "file:///" <> StringReplace[tempDir, "\\" -> "/"]]]];

	$lastElastixTemp = If[add =!= "" || Last[FileNameSplit[tempDir]] === "anat", DirectoryName[tempDir], tempDir];

	debugElastix["using as temp directory: " <> tempDir];
	debugElastix["$lastElastixTemp: " <> $lastElastixTemp];

	(*return temp directory*)
	tempDir
]

(* ::Subsubsection::Closed:: *)
(*RegisterData*)


Options[RegisterData] = {
	Iterations -> 250,
	Resolutions -> 1,
	HistogramBins -> 64,
	NumberSamples -> 10000,
	InterpolationOrderReg -> 3,
	BsplineSpacing -> 30,
	BsplineDirections -> {1,1,1},
	AffineDirections -> {1,1,1},
	MethodReg -> "affine",
	OutputImage -> True,
	TempDirectory -> "Default",
	DeleteTempDirectory -> True,
	PrintTempDirectory -> True,
	OutputTransformation -> False,
	UseGPU -> {False, Automatic},
	PCAComponents -> 1,
	ShowMetric -> False
};

SyntaxInformation[RegisterData] = {"ArgumentsPattern"->{_,_.,OptionsPattern[]}};


(* ::Subsubsection::Closed:: *)
(*RegisterData Series or PCA*)


(*Series or cyclic have no target definition so only one input*)
RegisterData[input_, opts:OptionsPattern[]]:=RegisterData[SplitRegInput[input], opts]

(*invalid input*)
RegisterData[$Failed, opts:OptionsPattern[]]:=Return[Message[RegisterData::inp];$Failed];

(*register series of data sets, vox definition, mask definition, no target definition*)
RegisterData[
	{series_?ArrayQ, mask_?ArrayQ, vox:{_?NumberQ,_?NumberQ,_?NumberQ}}, opts:OptionsPattern[]]:=Module[{
		depthS,dim,dimM,dimL,target,moving,dataout,voxL,output,cyclic,cyc,maskF,maskM
	},

	debugElastix["RegisterData: PCA or Series"];

	(*Check Method, Multi only possible for target and moving*)
	If[AnyTrue[OptionValue[MethodReg], (# === "rigidMulti" || # === "affineMulti" || # === "bsplineMulti") &], 
		Message[RegisterData::metC]; Return[Message[RegisterData::fatal]]];

	(*check for cyclic*)
	cyc = AnyTrue[Flatten[{OptionValue[MethodReg]}], (# === "PCAtranslation" || # === "PCArigid" || # === "PCAaffine" || # === "PCAbspline") &];
	cyclic = AllTrue[Flatten[{OptionValue[MethodReg]}], (# === "PCAtranslation" || # === "PCArigid" || # === "PCAaffine" || # === "PCAbspline") &];
	If[cyc =!= cyclic, Message[RegisterData::cyc]; Return[Message[RegisterData::fatal]]];


	(*get data properties*)
	depthS = ArrayDepth[series];
	dim = Dimensions[series];
	dimL = If[depthS==3, dim[[1]], dim[[2]]];
	dimM = Dimensions[mask];
	voxL = Length[vox];

	(*check dimensions*)
	(*series must be 3 of 4D*)
	If[!(depthS==3||depthS==4),Message[RegisterData::dims,depthS];Return[Message[RegisterData::fatal]]];
	(*series must have 2 or more volumes*)
	If[!dimL>=2,Message[RegisterData::vol,depthS,dim[[1]]];Return[Message[RegisterData::fatal]]];

	(*check voxel sizes*)
	If[voxL!=3||!(NumberQ@Total@vox),Message[RegisterData::voxS,vox];Return[Message[RegisterData::fatal]]];

	(*check mask*)
	If[mask!={1},
		If[cyclic,
			(*cyclic mask needs to be same dimensions as moving data*)
			If[dim!=dimM,Message[RegisterData::mask,dimM,dim];Return[Message[RegisterData::fatal]]],
			If[depthS==3,
				(*normal mask, one mask for all or one mask per volume*)
				If[!(dim[[2;;3]]==dimM||dim==dimM),Message[RegisterData::mask,dimM,dim];Return[Message[RegisterData::fatal]]],
				If[!(dim[[{1,3,4}]]==dimM||dim==dimM),Message[RegisterData::mask,dimM,dim];Return[Message[RegisterData::fatal]]]
			]
		]
	];

	
	(*check if method is cyclic*)
	If[cyclic,
		(*cyclic series define moving and target volumes*)
		target = moving = series;
		(*go to registration function*)
		RegisterDataI[{target,mask,vox}, {moving,mask,vox}, "PCA", opts]
		,
		(*normal series define moving and target volumes*)
		{target, moving} = If[depthS==3, {series[[1]],series[[2;;]]}, {series[[All,1]],Transpose@series[[All,2;;]]}];
		{maskF, maskM} = If[dimM==dim, If[depthS==3, {mask[[1]],mask[[2;;]]}, {mask[[All,1]],Transpose@mask[[All,2;;]]}], {mask,mask}];
		(*go to registration function*)
		output = RegisterDataI[{target,maskF,vox}, {moving,maskM,vox}, "series", opts];
		(*prepare output*)
		If[OptionValue[OutputTransformation],
			(*output data with transformation parameters*)
			dataout = Prepend[output[[1]],target];
			{If[depthS==4,Transpose@dataout,dataout],Prepend[output[[2]],{0,0,0,0,0,0,1,1,1,0,0,0}[[;;Length[output[[2,1]]]]]]}
			,
			(*output dat without transformation parameters*)
			dataout = Prepend[output,target];
			If[depthS==4,Transpose@dataout,dataout]
		]
	]
]


(* ::Subsubsection::Closed:: *)
(*RegisterData Volumes or Multi*)


(*Volumes or multi do have target definition, so two inputs*)
RegisterData[target_, moving_, opts:OptionsPattern[]]:=RegisterData[SplitRegInput[target], SplitRegInput[moving], opts]

(*invalid input*)
RegisterData[$Failed, _, opts:OptionsPattern[]]:=Return[Message[RegisterData::inp]; $Failed]
RegisterData[_ , $Failed, opts:OptionsPattern[]]:=Return[Message[RegisterData::inp]; $Failed]

(*register two data sets, mask and vox definition*)
RegisterData[
	{target_?ArrayQ, maskT_?ArrayQ, voxT:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving_?ArrayQ, maskM_?ArrayQ, voxM:{_?NumberQ,_?NumberQ,_?NumberQ}}, opts:OptionsPattern[]]:=Module[{
		depthT, depthM, voxTLength, voxMLength, dimT, dimM, type, output, mul ,multi
	},

	debugElastix["RegisterData: Volumes or Multi"];

	(*Check Method, PCA only possible for series*)
	If[AnyTrue[OptionValue[MethodReg], (# === "PCAtranslation" || # === "PCArigid" || # === "PCAaffine" || # === "PCAbspline") &], 
		Message[RegisterData::metC]; Return[Message[RegisterData::fatal]]];

	(*check for cyclic*)
	mul = AnyTrue[Flatten[{OptionValue[MethodReg]}], (# === "rigidMulti" || # === "affineMulti" || # === "bsplineMulti") &];
	multi = AllTrue[Flatten[{OptionValue[MethodReg]}], (# === "rigidMulti" || # === "affineMulti" || # === "bsplineMulti") &];
	If[mul =!= multi, Message[RegisterData::mult];Return[Message[RegisterData::fatal]]];


	(*get data properties*)
	depthT = ArrayDepth[target];
	depthM = ArrayDepth[moving];
	dimT = Dimensions[target];
	dimM = Dimensions[moving];
	voxTLength = Length[voxT];
	voxMLength = Length[voxM];

	debugElastix[{multi, depthM, depthT, depthM == depthT + 1}];

	(*check dimensions and determine type*)
	type = Which[
		multi && depthM == depthT, "multi",
		depthT == depthM, "vol", (*2D-2D, 3D-3D*)
		(depthT == 2 || depthT == 3) && depthM == depthT + 1, "series", (*2D-3D, 3D-4D multi volumes to single target*)
		(depthM == 2 || depthM == 3) && depthT == depthM + 1, "seriesI", (*3D-2D, 4D-3D one volume to multiple targets*)
		True, Message[RegisterData::dim, depthT, depthM]; Return[Message[RegisterData::fatal]] (*error*)];

	debugElastix["Type for registration: "<>type];

	(*check dimensions*)
	(*target and moving must be 2D or 3D*)

	(*check voxel size*)
	If[voxTLength!=3||voxMLength!=3||!(NumberQ@Total@voxT)||!(NumberQ@Total@voxM),Message[RegisterData::vox,voxT,voxM];Return[Message[RegisterData::fatal]]];

	
	(*define moving and target volumes*)
	output = RegisterDataI[
		{If[depthT==4, Transpose@target, target], maskT, voxT},
		{If[depthM==4, Transpose@moving, moving], maskM, voxM}, 
		type, opts];

	(*generate output*)
	If[OptionValue[OutputTransformation],
		{If[depthM==4||depthT===4, Transpose@output[[1]], output[[1]]], Prepend[output[[2]],{0,0,0,0,0,0,1,1,1,0,0,0}]},
		If[depthM==4||depthT===4, Transpose@output, output]
	]
]


(* ::Subsubsection::Closed:: *)
(*RegisterDataI*)


Options[RegisterDataI] = Options[RegisterData];

RegisterDataI[
	{target_?ArrayQ,voxT:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving_?ArrayQ,voxM:{_?NumberQ,_?NumberQ,_?NumberQ}}
, type_ , opts:OptionsPattern[]]:= RegisterDataI[{target,{1},voxT},{moving,{1},voxM},type,opts]

RegisterDataI[
	{target_?ArrayQ,maskT_,voxT:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving_?ArrayQ,voxM:{_?NumberQ,_?NumberQ,_?NumberQ}}
, type_ , opts:OptionsPattern[]]:= RegisterDataI[{target,maskT,voxT},{moving,{1},voxM},type,opts]

RegisterDataI[
	{target_?ArrayQ,voxT:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving_?ArrayQ,maskM_,voxM:{_?NumberQ,_?NumberQ,_?NumberQ}}
, type_, opts:OptionsPattern[]]:= RegisterDataI[{target,{1},voxT},{moving,maskM,voxM},type,opts]

RegisterDataI[
	{target_?ArrayQ,maskT_?ArrayQ,voxT:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving_?ArrayQ,maskM_?ArrayQ,voxM:{_?NumberQ,_?NumberQ,_?NumberQ}}, type_,OptionsPattern[]]:=Module[{
		tempDir, tempdir, elastix, parString, outputImg, iterations, resolutions,
		histogramBins, numberSamples, derivativeScaleA, derivativeScaleB, interpolationOrder,
		method, bsplineSpacing, data, vox, dimMov, dimTar, dimMovM, dimTarM, inputFolderI, moveFolderI, outFolderI,
		fixedF, movingF, outF, parF, depth, index, regPars, lenMeth, command, outFile,
		fMaskF, mMaskF, w, openCL, gpu, pca, dTar, lengthM, lengthT, dMov
	},

	w = {{0,0,0,0,0,0,1,1,1,0,0,0}};

	(*get option values*)
	outputImg=ToLowerCase[ToString[OptionValue[OutputImage]]];

	method = OptionValue[MethodReg];
	method = If[StringQ[method], {method}, method];
	debugElastix["RegisterDataI: "<>StringJoin[Riffle[method," - "]]<>" / "<>type];

	bsplineSpacing = OptionValue[BsplineSpacing];
	bsplineSpacing = If[!ListQ[bsplineSpacing],ConstantArray[bsplineSpacing,3],bsplineSpacing];
	derivativeScaleB = OptionValue[BsplineDirections];
	derivativeScaleA = OptionValue[AffineDirections];

	openCL = OptionValue[UseGPU];
	If[ListQ[openCL], {openCL, gpu} = openCL; gpu = If[gpu===Automatic, 0, gpu];, gpu = 0;];
	If[openCL, method = method /. {"rigidDTI"->"rigid", "affineDTI"->"affine"} ];
	pca = OptionValue[PCAComponents];

	iterations = OptionValue[Iterations];
	resolutions = OptionValue[Resolutions];
	histogramBins = OptionValue[HistogramBins];
	numberSamples = OptionValue[NumberSamples];
	interpolationOrder = OptionValue[InterpolationOrderReg];
	regPars = {iterations, resolutions, histogramBins, numberSamples, interpolationOrder};

	(*error sensitive checks*)

	(*find the elastix program*)
	elastix = GetAssetLocation["Elastix"];
	If[elastix=="error", Message[RegisterData::elastix]; Return[Message[RegisterData::fatal]]];

	(*check registration method*)
	If[!MemberQ[{
			"translation", "rigid", "similarity", "affine", "bspline", (*traditional*)
			"rigidDTI", "affineDTI", (*DTI specific*)
			"translationMask", "rigidMask", "similarityMask","affineMask","bsplineMask", (*Mask distance map*)
			"PCAtranslation", "PCArigid", "PCAaffine", "PCAbspline", (*PCA cyclic*)
			"rigidMulti", "affineMulti", "bsplineMulti" (*multi contrast*)
		},#],
		Message[RegisterData::met,#];
		Return[Message[RegisterData::fatal],Module]
		]&/@method; 
	lenMeth = Length[method];

	tempDir = CreateTempDirectory[OptionValue[TempDirectory], OptionValue[PrintTempDirectory], True];
	tempdir = tempDir<>$PathnameSeparator;

	(*create parameter list*)
	regPars = If[NumberQ[#], ConstantArray[#,lenMeth],
		If[Length[#]==lenMeth, #, Message[RegisterData::par,#,lenMeth]; Return[Message[RegisterData::fatal]]]
	]& /@ regPars;
	regPars = Transpose[regPars];

	(*get all data dimensions*)
	dimTar = Dimensions[target];
	dTar = ArrayDepth[target];
	lengthT = Length[target];

	dimMov = Dimensions[moving];
	dMov = ArrayDepth[moving];
	lengthM = Length[moving];
	
	debugElastix["Moving: ", {dimMov, dMov, lengthM}];
	debugElastix["Target: ", {dimTar, dTar, lengthT}];

	dimMovM = Dimensions[maskM];
	dimTarM = Dimensions[maskT];
	
	depth = Switch[type,
		"PCA", ToString[dTar-1]<>"D-t", 
		"multi"|"seriesI", ToString[dTar-1]<>"D",
		_,ToString[dTar]<>"D"];
	dTar = Which[
			type === "multi", {dTar-1, lengthM}, 
			type === "seriesI", {dTar-1, 1},
			True, {dTar, 1}];

	debugElastix[dTar];

	(*create parameter files*)
	parF = MapThread[(
		parString = ParString[#1, {#2, outputImg}, 
			{dTar, bsplineSpacing, derivativeScaleB, derivativeScaleA, pca}, 
			{openCL, gpu}];
		parF = "parameters-"<>#2<>".txt";
		Export[tempdir<>parF, parString];
		parF
	)&, {regPars, method}];

	debugElastix["parFiles: \n  - "<>StringRiffle[parF, "\n  - "]];

	(*perform registration which is either: "vol"|"PCA", "series" or "multi" based method  *)
	Switch[type,

		(*volume to volume registration (2D-2D, 3D-3D)*)
		(*cyclic volume to volume registration (2Dt-2Dt, 3Dt-3Dt)*)
		"vol"|"PCA",

		(*define folders*)
		{inputFolderI, moveFolderI, outFolderI} = {"", "", ""};

		(*Check if masks are needed*)
		{fMaskF, mMaskF} = {"", ""};
		If[dimTarM == dimTar && maskT!={1}, fMaskF="targetMask.nii"; 
			ExportNii[maskT,voxT,tempdir<>fMaskF]];
		If[dimMovM == dimMov && maskM!={1}, mMaskF="moveMask.nii"; 
			ExportNii[maskM,voxM,tempdir<>mMaskF]];

		(*Export target and moving data*)
		{fixedF, movingF, outF} = {"target-"<>depth<>".nii", "moving-"<>depth<>".nii", "result-"<>depth<>".nii.gz"};
		ExportNii[target, voxT, tempdir<>fixedF];
		ExportNii[moving, voxM, tempdir<>movingF];

		(*Create command and run elastix*)
		command = ElastixCommand[elastix, tempdir, parF, {inputFolderI, moveFolderI, outFolderI}, {fixedF, movingF, outF}, {fMaskF, mMaskF}][[1]];
		RunCommands[command];

		(*Import Results*)
		{data, vox}=ImportNii[tempdir<>outFolderI<>outF];

		,
		(*series to volume registration (2D-3D, 3D-4D)*)
		"series", 

		(*define folders*)
		{inputFolderI, moveFolderI, outFolderI} = {"", "", ""};

		(*Check if masks are needed*)
		{fMaskF, mMaskF} = {"", ""};
		If[dimTarM == dimTar && maskT!={1},	fMaskF="targetMask.nii"; 
			ExportNii[maskT, voxT, tempdir<>fMaskF]];

		(*Export target Data*)
		{fixedF, movingF, outF} = {"target-"<>depth<>".nii", "moving-"<>depth<>".nii", "result-"<>depth<>".nii.gz"};
		ExportNii[target, voxT, tempdir<>fixedF];

		(*export moving data, loop over series*)
		{command, outFile}=Transpose@(
		(
			index = StringPadInteger[#];
			(*define folders*)
			moveFolderI = outFolderI = "vol"<>index; CreateDirectory[tempdir<>outFolderI];
			(*Check if masks are needed*)
			If[(dimMovM == dimMov || dimMovM == Drop[dimMov,1]) && maskM!={1}, 
				mMaskF = moveFolderI<>$PathnameSeparator<>"moveMask.nii"; 
				ExportNii[If[dimMovM == dimMov, maskM[[#]], maskM], voxM, tempdir<>mMaskF]
			];
			(*export moving*)
			ExportNii[moving[[#]], voxM, tempdir<>moveFolderI<>$PathnameSeparator<>movingF];

			(*create command*)
			ElastixCommand[elastix, tempdir, parF, {inputFolderI, moveFolderI, outFolderI}, {fixedF, movingF, outF}, {fMaskF, mMaskF}]
		)&/@Range[lengthM]);

		(*Create and run batch*)
		RunCommands[command];

		(*Import results*)
		data = (First@ImportNii[#])&/@outFile;
		If[OptionValue[OutputTransformation], w = ReadTransformParameters[tempdir]];
		,

		(*series to volume registration (3D-4D, 4D-3D)*)
		"seriesI", 

		(*define folders*)
		{inputFolderI, moveFolderI, outFolderI} = {"", "", ""};		
		{fMaskF, mMaskF} = {"", ""};
		{fixedF, movingF, outF} = {"target-"<>depth<>".nii", "moving-"<>depth<>".nii", "result-"<>depth<>".nii.gz"};

		(*export target data, loop over series*)
		{command, outFile}=Transpose@(
		(
			index = StringPadInteger[#];
			(*define folders*)
			inputFolderI = moveFolderI = outFolderI = "vol"<>index; CreateDirectory[tempdir<>outFolderI];

			(*Check if masks are needed*)
			If[(dimMovM == dimMov || dimMovM == Drop[dimMov,1]) && maskM!={1}, 
				mMaskF = moveFolderI<>$PathnameSeparator<>"moveMask.nii"; 
				ExportNii[If[dimMovM == dimMov, maskM[[#]], maskM], voxM, tempdir<>mMaskF]
			];
			If[(dimTarM == dimTar || dimTarM == Drop[dimTar,1]) && maskM!={1}, 
				fMaskF = inputFolderI<>$PathnameSeparator<>"targetMask.nii"; 
				ExportNii[If[dimTarM == dimTar, maskT[[#]], maskT], voxT, tempdir<>fMaskF]
			];
			(*Export moving data*)
			ExportNii[moving, voxM, tempdir<>moveFolderI<>$PathnameSeparator<>movingF];
			(*export target data*)
			ExportNii[target[[#]], voxT, tempdir<>inputFolderI<>$PathnameSeparator<>fixedF];

			(*create command*)
			ElastixCommand[elastix, tempdir, parF, {inputFolderI, moveFolderI, outFolderI}, {fixedF, movingF, outF}, {fMaskF, mMaskF}]
		)&/@Range[lengthT]);

		(*Create and run batch*)
		RunCommands[command];

		(*Import results*)
		data = (First@ImportNii[#])&/@outFile;
		If[OptionValue[OutputTransformation], w = ReadTransformParameters[tempdir]];

		,
		(*if not series or vol then PCA based method*)
		"multi", 

		(*define folders*)
		{inputFolderI, moveFolderI, outFolderI} = {"", "", ""};

		(*Check if masks are needed*)
		{fMaskF, mMaskF} = {"", ""};
		If[Drop[dimTar, 1] == dimTarM && maskT!={1}, fMaskF="targetMask.nii"; ExportNii[maskT,voxT,tempdir<>fMaskF]];
		If[Drop[dimMov, 1] == dimMovM && maskM!={1}, mMaskF="moveMask.nii"; ExportNii[maskM,voxM,tempdir<>mMaskF]];

		(*Export target and moving data*)
		{fixedF, movingF, outF} = {"target-"<>depth<>#<>".nii"&, "moving-"<>depth<>#<>".nii"&, "result-"<>depth<>".nii.gz"};
		(
			index = StringPadInteger["-",#];
			ExportNii[target[[#]], voxT, tempdir<>fixedF[index]];
			ExportNii[moving[[#]], voxM, tempdir<>movingF[index]];
		)&/@Range[lengthM];

		(*Create command and run elastix*)
		command = ElastixCommand[elastix, tempdir, parF, {inputFolderI, moveFolderI, outFolderI}, {fixedF, movingF, outF}, {fMaskF, mMaskF}, lengthM][[1]];
		RunCommands[command];

		(*perform translation on all files *)
		debugElastix["TransformData: making multi output"];
		data = TransformData[{#, voxM}, TempDirectory->DirectoryName[tempDir], 
			DeleteTempDirectory->False, PrintTempDirectory->False]&/@moving;
	];

	(*do some cleanup*)
	If[OptionValue[ShowMetric], Print[ListLinePlot[Flatten[Import[#, "Data"][[2 ;;, 2]]& /@ FileNames["IterationInfo*", tempdir]]]]];
	If[OptionValue[DeleteTempDirectory], DeleteDirectory[tempdir, DeleteContents->True]];

	(*output results*)
	data = ToPackedArray[N@data];
	data = Floor[Clip[data, MinMax[moving]], 10.^-8];
	If[OptionValue[OutputTransformation], {data, w}, data]
]


(* ::Subsubsection::Closed:: *)
(*RegisterDataSplit*)


Options[RegisterDataSplit] = Join[Options[RegisterData],{SplitMethod->"Mean"}];

SyntaxInformation[RegisterDataSplit] = {"ArgumentsPattern" -> {_, _., OptionsPattern[]}};

RegisterDataSplit[targetI_, movingI_, opts : OptionsPattern[]] := Block[{
	reg, mov, target ,maskT, voxT, moving, maskM, voxM,
	targetLeft, targetRight, maskTl, maskTr, cut1, movingLeft, movingRight, maskMl, maskMr, cut2,
	regLeft, regRight
	},

	(*prepare the input*)
	{target ,maskT, voxT} = SplitRegInput[targetI];
	{moving, maskM, voxM} = SplitRegInput[movingI];

	(*find the common split*)	
	{targetLeft, targetRight, cut1} = CutData[target];
	{movingLeft, movingRight, cut2} = CutData[moving];

	{cut1, cut2} = Switch[OptionValue[SplitMethod],
		"target", Round[{cut1, (cut1 voxT[[2]])/voxM[[2]]}],
		"moving", Round[{(cut2 voxM[[2]])/voxT[[2]], cut2}],
		"nearest", Round[First@Nearest[{cut1 Last@voxT, cut2 Last@voxM}, (Last@Dimensions[target]/2) Last[voxT]]/{Last@voxT, Last@voxM}],
		"own", Round[{cut1, cut2}],
		_, Round[Mean[{cut1 voxT[[2]], cut2 voxM[[2]]}]/{voxT[[2]], voxM[[2]]}]
	];

	(*cut data*)
	{targetLeft, targetRight, cut1} = CutData[target,cut1];
	{movingLeft, movingRight, cut2} = CutData[moving,cut2];
	(*cut masks*)
	{maskTl, maskTr} = If[maskT==={1}, {{1},{1}}, CutData[maskT,cut1][[;;-2]]];
	{maskMl, maskMr} = If[maskM==={1}, {{1},{1}}, CutData[maskM,cut2][[;;-2]]];

	(*register left part*)
	regLeft = RegisterData[{targetLeft, maskTl, voxT}, {movingLeft, maskMl, voxM},Sequence@@FilterRules[{opts}, Options[RegisterData]]];
	(*register right part*)
	regRight = RegisterData[{targetRight, maskTr, voxT}, {movingRight, maskMr, voxM},Sequence@@FilterRules[{opts}, Options[RegisterData]]];

	StichData[regLeft,regRight]
]


(* ::Subsubsection::Closed:: *)
(*ReadTransformParameters*)


SyntaxInformation[ReadTransformParameters]={"ArgumentsPattern"->{_}};

ReadTransformParameters[dir_] := Block[{files, fileNum, cor, pars},
	(*get all the transform files and sort them*)
	files = FileNames["TransformParameters*", dir, 3];
	fileNum = If[Length[files] == 1, {1}, ToExpression[First[StringCases[FileNameSplit[#][[-2]], DigitCharacter ..]]] & /@ files];
	files = files[[Ordering[fileNum]]];

	(*read and parse the parameter file*)
	pars = (((First[#] -> ToExpression[Rest[#]]) &[StringSplit[StringTake[#, {2, -2}]]]) & /@ Select[DeleteCases[Import[#, "Lines"], ""], StringTake[#, 2] =!= "//" &]) & /@ files;

	(*extract the trans*)
	cor = Partition[#, 3] & /@ ("TransformParameters" /. pars);
	debugElastix[{cor, Length@cor}];
	If[Length[First@cor]===4,
		cor = #[[{1, 4, 3, 2}, {3, 2, 1}]]& /@ cor;
		cor[[All, 1]] = cor[[All, 1]] / Degree;
		Flatten /@ cor,
		First /@ cor
	]
]


(* ::Subsection:: *)
(*TransformData*)


(* ::Subsubsection::Closed:: *)
(*TransformData*)


Options[TransformData] = {
	TempDirectory -> "Default",
	PrintTempDirectory->True, 
	DeleteTempDirectory -> "All", 
	Method -> "Default",
	FindTransform -> "Auto",
	ImportDeformation -> False
}

SyntaxInformation[TransformData] = {"ArgumentsPattern" -> {_, OptionsPattern[]}};

TransformData[{data_, vox_}, ops:OptionsPattern[]] := Block[{
		met, def, tempDir, dat, command, output, index, outFile, tempDirI, defFile, deform
	},

	{met, def} = OptionValue[{Method, ImportDeformation}];
	dat = If[ArrayDepth[data]===4, Transpose@data, data];
	tempDir = If[OptionValue[TempDirectory] === "Default", $lastElastixTemp, OptionValue[TempDirectory]];
	debugElastix["transform using as temp directory: " <> tempDir];
	debugElastix[def];

	output = Switch[met,
	
		"Loop",
		(*Loop over multi dimensions when set by user*)
		dat = TransformData[{#, vox}, Method->"Default", DeleteTempDirectory->False, ops]&/@dat;
		If[ArrayDepth[data]===4, Transpose@dat, dat]
		,

		"multi"|"vols",

		(*get the correct temp directory*)
		If[met === "vols",
			debugElastix["Placing transform folder in "<>tempDir<>"\\vols*"],
			debugElastix["Placing multiple transform folders in "<>tempDir]
		];

		(*loop over folders*)
		{command, outFile, defFile, tempDir} = Transpose[(
			index = StringPadInteger[#];
			tempDirI = If[met === "vols",
				FileNameJoin[{tempDir, "vol"<>index, "trans"}],
				FileNameJoin[{tempDir, "trans"<>index}]];
			If[#===1 || #== Length[dat], debugElastix[tempDirI]];

			ExportNii[dat[[#]], vox, FileNameJoin[{tempDirI, "trans.nii"}]];
			command = TransformixCommand[tempDirI, True];
			outFile = FileNameJoin[{tempDirI, "result.nii"}];
			defFile = FileNameJoin[{tempDirI, "deformationField.nii"}];

			{command, outFile, defFile, tempDirI}
		)&/@Range[Length@dat]];

		(*Create and run batch*)
		RunCommands[command, "T"];

		(*Import results*)
		output = First[ImportNii[#]]&/@outFile;
		If[def, 
			deform = Transpose[First[ImportNii[#]][[All,1]]]&/@defFile;
			debugElastix[Dimensions@deform];
			{output, deform}, 
			output
		]
		,

		_,
		(*perform normal transform for single volume*)
		(*define the directory*)
		tempDir = FileNameJoin[{tempDir, "transform"}];

		(*Export and transform*)
		ExportNii[dat, vox, FileNameJoin[{tempDir, "trans.nii"}]];
		command = TransformixCommand[tempDir, True];
		outFile = FileNameJoin[{tempDir, "result.nii"}];
		defFile = FileNameJoin[{tempDir, "deformationField.nii"}];

		RunCommands[command, "T"];

		output = First[ImportNii[outFile]];
		If[def, 
			deform = Transpose[First[ImportNii[defFile]][[All,1]]];
			{output, deform}, 
			output
		]
	];

	If[OptionValue[DeleteTempDirectory], DeleteDirectory[#, DeleteContents -> True] &/@ Flatten[{tempDir}]];

	(*give the output*)
	If[def, {output, deform} = output];

	output = ToPackedArray@N@output;
	output = If[ArrayDepth[data]===4, Transpose@output, output];
	output = Floor[Clip[output, MinMax[data]], 10.^-8];

	If[def, 
		deform = ToPackedArray@N@deform;
		deform = If[ArrayDepth[data]===4, Transpose@deform, deform];
		{output, deform},
		output
	]
]


(* ::Subsection:: *)
(*RegisterDataTransform/Split*)


(* ::Subsubsection::Closed:: *)
(*RegisterDataTransform*)


Options[RegisterDataTransform] = Join[Options[RegisterData], {
	TransformMethod->"Data",
	ImportDeformation -> False
}];

SyntaxInformation[RegisterDataTransform] = {"ArgumentsPattern" -> {_, _, _, OptionsPattern[]}};

RegisterDataTransform[target_, moving_, moving2_, opts : OptionsPattern[]]:=RegisterDataTransform[target, moving, SplitRegInput[moving2], opts]

RegisterDataTransform[_, _, $Failed, opts : OptionsPattern[]]:=Return[Message[RegisterData::inp]; $Failed]

RegisterDataTransform[target_, moving_, {mov_, _, vox_}, opts : OptionsPattern[]] := Block[{
		tempDir, opt, reg, movD, regD, trans
	},

	tempDir= CreateTempDirectory[OptionValue[TempDirectory], OptionValue[PrintTempDirectory]];
	opt = Sequence[DeleteTempDirectory -> False, PrintTempDirectory -> False, 
		TempDirectory -> tempDir, ImportDeformation -> OptionValue[ImportDeformation]];

	reg = RegisterData[target, moving, Sequence@@FilterRules[Join[{opt}, {opts}], Options[RegisterData]]];

	(*for segmentations and masks you want the interpolation order to be 0*)
	If[OptionValue[TransformMethod]=!="Data", ReplaceIntOrder[tempDir]];

	movD = ArrayDepth[mov];
	regD = ArrayDepth[reg];

	debugElastix["Dimensions reg/mov", {regD, movD}];

	trans = Which[
		regD == 3 && movD == 3, TransformData[{mov, vox}, opt],
		regD == 3 && movD == 4, TransformData[{mov, vox}, opt, Method->"multi"],
		regD == 4 && movD == 4, TransformData[{mov, vox}, opt, Method->"vols"],
		regD == 4 && movD == 3, TransformData[{Transpose[ConstantArray[mov, Length[reg[[1]]]]], vox}, opt, Method->"vols"],
		movD === regD && movD === 4, TransformData[{mov, vox}, opt, Method->"vols"],
		movD === regD, TransformData[{mov, vox}, opt],
		True, TransformData[{mov, vox}, opt]
	];

	If[OptionValue[DeleteTempDirectory], DeleteDirectory[tempDir, DeleteContents->True]];		
	{reg, trans}
]


ReplaceIntOrder[dir_]:=ReplaceIntOrder[dir, 0]

ReplaceIntOrder[dir_, int_] := Block[{files, text, text2},
	files = FileNames["TransformParameters*.txt", dir, Infinity];
	Do[
		text = Import[f, "Text"];
		text2 = StringReplace[text, 
			RegularExpression["\\(FinalBSplineInterpolationOrder \\d+\\)"] -> "(FinalBSplineInterpolationOrder "<>ToString[int]<>")"];
		If[text =!= text2, Export[f, text2, "Text"]];
	, {f, files}];
]


(* ::Subsubsection::Closed:: *)
(*RegisterDataTransformSplit*)


Options[RegisterDataTransformSplit] = Join[Options[RegisterData],{SplitMethod->"Mean", TransformMethod->"Data"}];

SyntaxInformation[RegisterDataTransformSplit] = {"ArgumentsPattern" -> {_, _, _, OptionsPattern[]}};

RegisterDataTransformSplit[targetI_, movingI_, {moving2_, vox_}, opts : OptionsPattern[]] := Block[{reg, mov,
	target ,maskT, voxT, moving, maskM, voxM,
	targetLeft, targetRight, maskTl, maskTr, cut1, movingLeft, movingRight, maskMl, maskMr, cut2,
	moving2l, moving2r, tempDir, regLeft, regRight
	},

	(*prepare the input*)
	{target ,maskT, voxT} = SplitRegInput[targetI];
	{moving, maskM, voxM} = SplitRegInput[movingI];

	(*find the common split*)	
	{targetLeft, targetRight, cut1} = CutData[target];
	{movingLeft, movingRight, cut2} = CutData[moving];

	{cut1, cut2} = Switch[OptionValue[SplitMethod],
		"Target", Round[{cut1, (cut1 voxT[[2]])/voxM[[2]]}],
		"Moving", Round[{(cut2 voxM[[2]])/voxT[[2]], cut2}],
		"Nearest", Round[First@Nearest[{cut1 Last@voxT, cut2 Last@voxM}, (Last@Dimensions[target]/2) Last[voxT]]/{Last@voxT, Last@voxM}],
		"own", Round[{cut1, cut2}],
		_, Round[Mean[{cut1 voxT[[2]], cut2 voxM[[2]]}]/{voxT[[2]], voxM[[2]]}]
		];

	(*cut data*)
	{targetLeft, targetRight, cut1} = CutData[target,cut1];
	{movingLeft, movingRight, cut2} = CutData[moving,cut2];
	(*cut masks*)
	{maskTl, maskTr} = If[maskT === {1}, {{1}, {1}}, CutData[maskT,cut1][[;;-2]]];
	{maskMl, maskMr} = If[maskM === {1}, {{1}, {1}}, CutData[maskM,cut2][[;;-2]]];

	(*split the moving2 data*)
	{moving2l, moving2r, cut2} = CutData[moving2, cut2];

	{regLeft, movingLeft} = RegisterDataTransform[{targetLeft, maskTl, voxT}, {movingLeft, maskMl, voxM}, {moving2l, vox}, Sequence@@FilterRules[{opts}, Options[RegisterDataTransform]]];

	{regRight, movingRight} = RegisterDataTransform[{targetRight, maskTr, voxT}, {movingRight, maskMr, voxM}, {moving2r, vox}, Sequence@@FilterRules[{opts}, Options[RegisterDataTransform]]];

	{StichData[regLeft, regRight], StichData[movingLeft, movingRight]}
]


(* ::Subsection:: *)
(*RegisterDiffusionData/Split*)


(* ::Subsubsection::Closed:: *)
(*RegisterDiffusionData*)


Options[RegisterDiffusionData] = Join[
	Options[RegisterData] /. {{1, 1, 1} -> {0, 1, 1}, "affine" -> "affineDTI", "rigid" -> "rigidDTI"},{
	IterationsA -> 1000, 
	ResolutionsA -> 1, 
	HistogramBinsA -> 64,
	NumberSamplesA -> 20000,
	InterpolationOrderRegA -> 1,
	MethodRegA -> {"rigid", "bspline"},
	RegistrationTarget->"Fist"
}];

SyntaxInformation[RegisterDiffusionData] = {"ArgumentsPattern" -> {_, _., OptionsPattern[]}};

(*No anatomical data, goto RegisterData*)
RegisterDiffusionData[
	{dtiData_?ArrayQ, vox : {_?NumberQ, _?NumberQ, _?NumberQ}}
,opts : OptionsPattern[]] := RegisterDiffusionData[{dtiData, {1}, vox}, opts]

RegisterDiffusionData[
	{dtiData_?ArrayQ, dtiMask_?ArrayQ, vox : {_?NumberQ, _?NumberQ, _?NumberQ}}
,opts:OptionsPattern[]] := Block[{met},
	debugElastix["Diffusion registration"];
	met = (OptionValue[MethodReg] /. {"affine" -> "affineDTI", "rigid" -> "rigidDTI"});
	RegisterData[{dtiData, dtiMask, vox},(*OutputTransformation->True,*) 
		MethodReg-> met,
		AffineDirections -> {1, 1, 1}, FilterRules[{opts}, Options[RegisterData]]]
]

(*Anatomical data present, define two registrations*)
RegisterDiffusionData[
	{dtiData_?ArrayQ, vox : {_?NumberQ, _?NumberQ, _?NumberQ}},
	{anatData_?ArrayQ, voxAnat : {_?NumberQ, _?NumberQ, _?NumberQ}}
,opts : OptionsPattern[]] := RegisterDiffusionData[{dtiData, {1}, vox}, {anatData, {1},voxAnat}, opts]

RegisterDiffusionData[
	{dtiData_?ArrayQ, dtiMask_?ArrayQ, vox : {_?NumberQ, _?NumberQ, _?NumberQ}},
	{anatData_?ArrayQ, voxAnat : {_?NumberQ, _?NumberQ, _?NumberQ}}
,opts : OptionsPattern[]] := RegisterDiffusionData[{dtiData, dtiMask, vox}, {anatData, {1}, voxAnat}, opts]

RegisterDiffusionData[
	{dtiData_?ArrayQ, vox : {_?NumberQ, _?NumberQ, _?NumberQ}},
	{anatData_?ArrayQ, anatMast_?ArrayQ, voxAnat : {_?NumberQ, _?NumberQ, _?NumberQ}}
,opts : OptionsPattern[]] := RegisterDiffusionData[{dtiData, {1}, vox}, {anatData, anatMast, voxAnat}, opts]

RegisterDiffusionData[
	{dtiData_?ArrayQ, dtiMask_?ArrayQ, vox : {_?NumberQ, _?NumberQ, _?NumberQ}},
	{anatData_?ArrayQ, anatMast_?ArrayQ, voxAnat : {_?NumberQ, _?NumberQ, _?NumberQ}},opts : OptionsPattern[]] := Module[{
		dtiDataReg, tempDir, tempDirA, volDirs, w,tFilesA, tFilesD, dtiDataRegA, cmd, target, movingData, volDir
	},

	tempDir = CreateTempDirectory[OptionValue[TempDirectory], OptionValue[PrintTempDirectory], True];
	tempDirA = tempDir <> $PathnameSeparator <> "anat";

	(*perform DTI registration*)
	debugElastix["Diffusion registration"];	
	dtiDataReg = RegisterData[{dtiData, dtiMask, vox},
		TempDirectory -> tempDir, 
		DeleteTempDirectory -> False, 
		PrintTempDirectory -> False,
		OutputTransformation->OptionValue[OutputTransformation], 
		MethodReg-> (OptionValue[MethodReg] /. {"affine" -> "affineDTI", "rigid" -> "rigidDTI"}),
		(*AffineDirections -> {1, 1, 1},*)
		FilterRules[{opts} , Options[RegisterData]]
	];

	If[OptionValue[OutputTransformation], {dtiDataReg,w} = dtiDataReg];

	target = OptionValue[RegistrationTarget];
	movingData = If[ListQ[target] && AllTrue[target, IntegerQ] && Min[target] > 0 && Max[target] <= Length[dtiDataReg[[1]]],
		Median /@ dtiDataReg[[All, DeleteDuplicates[target]]],
		Switch[target,
			"Median", Median@Transpose@dtiDataReg,
			"First", First@Transpose@dtiDataReg,
			_, Mean@Transpose@dtiDataReg
		]
	];

	(*perform anat registration*)
	debugElastix["Anatomy registration"];
	RegisterData[{anatData, anatMast, voxAnat}, {movingData, vox},
		TempDirectory -> tempDirA, 
		DeleteTempDirectory -> False,
		Iterations -> OptionValue[IterationsA], 
		Resolutions -> OptionValue[ResolutionsA],
		HistogramBins -> OptionValue[HistogramBinsA], 
		NumberSamples -> OptionValue[NumberSamplesA],
		InterpolationOrderReg -> OptionValue[InterpolationOrderRegA],
		BsplineSpacing -> OptionValue[BsplineSpacing], 
		BsplineDirections -> OptionValue[BsplineDirections],
		AffineDirections -> OptionValue[AffineDirections],
		MethodReg -> OptionValue[MethodRegA]/. {"affine" -> "affineDTI", "rigid" -> "rigidDTI"}, 
		FilterRules[{opts}, Options[RegisterData]]
	];

	(*transform all diffusion files to anatomy*)
	debugElastix["Combine transforms"];

	(*export diffusion reg target*)
	volDir = FileNameJoin[{tempDir,"vol"<>StringPadInteger[0]}];
	CreateDirectory[volDir];
	ExportNii[dtiDataReg[[All,1]],vox,FileNameJoin[{volDir,"moving-3D.nii"}]];

	(*get vol folders and anat transform files*)
	volDirs = FileNames["vol*", tempDir, 1];
	tFilesA = FileNames["TransformParameters*", tempDirA];

	(*create Final Transform files*)
	(
		tFilesD = FileNames["TransformParameters*", #];
		ConcatenateTransformFiles[Join[tFilesD, tFilesA], #]
	) & /@ volDirs;

	(*call transformix*)
	cmd = TransformixCommand[tempDir, False];
	PrintTemporary["Combining transformations"];
	RunCommands[cmd, "T"];

	(*import dti data in anat space*)
	dtiDataRegA = Transpose[ImportNii[#][[1]] & /@ FileNames["resultA*", tempDir, 2]];

	(*finalize by deleting temp director*)
	If[OptionValue[DeleteTempDirectory],DeleteDirectory[tempDir,DeleteContents->True]];

	(*output data*)
	If[OptionValue[OutputTransformation],
		{dtiDataReg, dtiDataRegA, w},
		{dtiDataReg, dtiDataRegA}
	]
]


(* ::Subsubsection::Closed:: *)
(*RegisterDiffusionDataSplit*)


Options[RegisterDiffusionDataSplit] := Options[RegisterDiffusionData];

SyntaxInformation[RegisterDiffusionDataSplit] = {"ArgumentsPattern" -> {_, _., OptionsPattern[]}};

RegisterDiffusionDataSplit[
	{data_, vox: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	opts : OptionsPattern[]] := Block[
		{dataLeft, dataRight, cut},

	{dataLeft, dataRight, cut} = CutData[data];
	dataLeft = RegisterDiffusionData[{dataLeft, vox}, opts];
	dataRight = RegisterDiffusionData[{dataRight, vox}, opts];
	StichData[dataLeft, dataRight]
];

RegisterDiffusionDataSplit[
	{data_, mask_, vox: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	opts : OptionsPattern[]] := Block[
		{dataLeft, dataRight, cut, maskRight, maskLeft},

	{dataLeft, dataRight, cut} = CutData[data];
	{maskLeft, maskRight, cut} = CutData[mask,cut];
	dataLeft = RegisterDiffusionData[{dataLeft, maskLeft, vox}, opts];
	dataRight = RegisterDiffusionData[{dataRight, maskRight, vox}, opts];
	StichData[dataLeft, dataRight]
];

RegisterDiffusionDataSplit[
	{data_, vox: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	{dataAnat_, voxAnat: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	opts : OptionsPattern[]] := Block[
		{dataLeft, dataRight, dataAnatLeft, dataAnatRight, cut1, cut2},

	(*find cuts*)
	{dataLeft, dataRight, cut1} = CutData[data];
	{dataAnatLeft, dataAnatRight, cut2} = CutData[dataAnat];

	(*align cuts*)
	{cut1,cut2}=Round[First@Nearest[{cut1 Last@vox, cut2 Last@voxAnat}, Round[Last@Dimensions[data]/2] Last@vox] / {Last@vox, Last@voxAnat}];
	(*{cut1,cut2}=Round[Mean[{cut1 vox[[2]], cut2 voxAnat[[2]]}]/{vox[[2]],voxAnat[[2]]}];*)

	(*cut with the aligned cuts*)
	{dataLeft, dataRight, cut1} = CutData[data, cut1];
	{dataAnatLeft, dataAnatRight, cut2} = CutData[dataAnat, cut2];

	dataLeft = RegisterDiffusionData[{dataLeft, vox}, {dataAnatLeft, voxAnat}, opts][[2]];
	dataRight = RegisterDiffusionData[{dataRight, vox}, {dataAnatRight, voxAnat}, opts][[2]];
	StichData[dataLeft, dataRight]
];

RegisterDiffusionDataSplit[
	{data_, mask_, vox: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	{dataAnat_, voxAnat: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	opts : OptionsPattern[]] := Block[
		{dataLeft, dataRight, dataAnatLeft, dataAnatRight, maskLeft, maskRight, cut1,cut2},

	(*find cuts*)
	{dataLeft, dataRight, cut1} = CutData[data];
	{dataAnatLeft, dataAnatRight, cut2} = CutData[dataAnat];

	(*align cuts*)
	{cut1,cut2}=Round[First@Nearest[{cut1 Last@vox, cut2 Last@voxAnat}, Round[Last@Dimensions[data]/2] Last@vox] / {Last@vox, Last@voxAnat}];
	(*{cut1,cut2}=Round[Mean[{cut1 vox[[2]], cut2 voxAnat[[2]]}]/{vox[[2]],voxAnat[[2]]}];*)

	(*cut with the aligned cuts*) 
	{dataLeft, dataRight, cut1} = CutData[data,cut1];
	{maskLeft, maskRight, cut1} = CutData[mask,cut1];
	{dataAnatLeft, dataAnatRight, cut2} = CutData[dataAnat,cut2];

	dataLeft = RegisterDiffusionData[{dataLeft, maskLeft, vox}, {dataAnatLeft, voxAnat}, opts][[2]];
	dataRight = RegisterDiffusionData[{dataRight, maskRight, vox}, {dataAnatRight, voxAnat}, opts][[2]];

	StichData[dataLeft, dataRight]
];

RegisterDiffusionDataSplit[
	{data_, mask_, vox: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	{dataAnat_, maskAnat_, voxAnat: {_?NumberQ, _?NumberQ, _?NumberQ}}, 
	opts : OptionsPattern[]] := Block[
		{dataLeft, dataRight, dataAnatLeft, dataAnatRight, maskLeft, maskRight, maskAnatLeft, maskAnatRight,cut1,cut2},

	(*find cuts*)
	{dataLeft, dataRight, cut1} = CutData[data];
	{dataAnatLeft, dataAnatRight, cut2} = CutData[dataAnat];

	(*align cuts*)
	{cut1,cut2}=Round[First@Nearest[{cut1 Last@vox, cut2 Last@voxAnat}, Round[Last@Dimensions[data]/2] Last@vox] / {Last@vox, Last@voxAnat}];
	(*{cut1,cut2}=Round[Mean[{cut1 vox[[2]], cut2 voxAnat[[2]]}]/{vox[[2]],voxAnat[[2]]}];*)

	(*cut with the aligned cuts*) 
	{dataLeft, dataRight, cut1} = CutData[data,cut1];
	{maskLeft, maskRight, cut1} = CutData[mask,cut1];
	{dataAnatLeft, dataAnatRight, cut2} = CutData[dataAnat,cut2];
	{maskAnatLeft, maskAnatRight, cut2} = CutData[maskAnat,cut2];

	dataLeft = RegisterDiffusionData[{dataLeft, maskLeft, vox}, {dataAnatLeft, maskAnatLeft, voxAnat}, opts][[2]];
	dataRight = RegisterDiffusionData[{dataRight, maskRight, vox}, {dataAnatRight, maskAnatRight, voxAnat}, opts][[2]];

	StichData[dataLeft, dataRight]
];


(* ::Subsection::Closed:: *)
(*RegisterTensorData*)


Options[RegisterTensorData]=Options[RegisterData];

SyntaxInformation[RegisterTensorData]={"ArgumentsPattern"->{_,_,_.,OptionsPattern[]}};

RegisterTensorData[target_,moving_,opts:OptionsPattern[]]:=RegisterTensorData[SplitRegInput[target],SplitRegInput[moving],{{1},{1},{1,1,1}},opts]

RegisterTensorData[target_,moving_,moving2_,opts:OptionsPattern[]]:=RegisterTensorData[SplitRegInput[target],SplitRegInput[moving],SplitRegInput[moving2],opts]

RegisterTensorData[$Failed, _, _, opts:OptionsPattern[]]:=Return[Message[RegisterData::inp];$Failed]
RegisterTensorData[_, $Failed, _, opts:OptionsPattern[]]:=Return[Message[RegisterData::inp];$Failed]
RegisterTensorData[_, _, $Failed, opts:OptionsPattern[]]:=Return[Message[RegisterData::inp];$Failed]

RegisterTensorData[
	{target_?ArrayQ,maskT_?ArrayQ,voxT:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving_?ArrayQ,maskM_?ArrayQ,voxM:{_?NumberQ,_?NumberQ,_?NumberQ}},
	{moving2_?ArrayQ,_?ArrayQ,vox:{_?NumberQ,_?NumberQ,_?NumberQ}}, opts:OptionsPattern[]]:=Block[{
		trans, coor, coorM, tarI, movI, met, mov2, vox2, reg, reg2, tensR, disp
	},

	trans = moving2=!={1};

	(*get coordinates*)
	coor = MakeCoordinates[Dimensions@If[trans, target, target[[1]]],voxT];
	coorM = MakeCoordinates[Dimensions@If[trans, moving2[[1]], moving[[1]]], If[trans, vox, voxM]];

	(*make the moving and target data*)
	tarI = If[trans, target, Transpose[LogTensor@target]];
	movI = If[trans, moving, Transpose[LogTensor@moving]];
	mov2 = Transpose@If[trans, Join[LogTensor@moving2, coorM], coorM];
	vox2 = If[trans, vox, voxM];

	(*perform the registration of tens and coor*)
	met = OptionValue[MethodReg]/.If[trans,{},{"rigid"->"rigidMulti","affine"->"affineMulti","bspline"->"bsplineMulti"}];
	{reg, reg2} = RegisterDataTransform[{tarI, maskT, voxT}, {movI, maskM, voxM}, {mov2, vox}, MethodReg->met, InterpolationOrderReg->1, opts];

	(*correct the tensor for deformation*)
	tensR = ExpTensor@If[trans, Transpose[reg2[[All,;;6]]], Transpose[reg]];
	coorM = If[trans, Transpose@reg2[[All,7;;]], Transpose@reg2];
	disp = MaskData[coorM-coor, Times@@((Mask[#,5])&/@coorM)];
	tensR = TransformTensor[tensR, disp, voxT];

	(*generate the output*)
	If[trans, {reg, tensR}, tensR]
]


(* ::Subsection::Closed:: *)
(*RegisterCardiacData*)


Options[RegisterCardiacData]=Join[{RegistrationTarget->"Mean"},Options[RegisterData]];

SyntaxInformation[RegisterCardiacData]={"ArgumentsPattern"->{_,OptionsPattern[]}};

(*data only*)
RegisterCardiacData[data_?ArrayQ, opts:OptionsPattern[]]:=RegisterCardiacData[{data,{1},{1,1,1}},opts]
(*data with voxel*)
RegisterCardiacData[{data_?ArrayQ, vox:{_?NumberQ,_?NumberQ,_?NumberQ}}, opts:OptionsPattern[]]:=RegisterCardiacData[{data,{1},vox},opts]
(*data with mask*)
RegisterCardiacData[{data_?ArrayQ ,mask_?ArrayQ}, opts:OptionsPattern[]]:=RegisterCardiacData[{data,mask,{1,1,1}},opts]
(*data with mask and voxel*)
RegisterCardiacData[{data_?ArrayQ, mask_?ArrayQ, vox:{_?NumberQ,_?NumberQ,_?NumberQ}}, opts:OptionsPattern[]]:=Block[
	{tempDir, dataRight, slices, maskRight, i, size, target},

	tempDir = CreateTempDirectory[OptionValue[TempDirectory], OptionValue[PrintTempDirectory], True];

	(*check if data is 3D or 4D*)
	slices = Range[Length[data]];
	size = Length[data[[1]]];
	maskRight = If[mask=={1}, ConstantArray[1,Dimensions[data[[All,1]]]],mask];

	target=If[OptionValue[MethodReg]==="PCAtranslation"||OptionValue[MethodReg]==="PCArigid"||OptionValue[MethodReg]==="PCAaffine"||OptionValue[MethodReg]==="PCAbspline",
		"stack",
		OptionValue[RegistrationTarget]
	];

	(*monitor over slices*)
	Monitor[
		i=0;
		dataRight = Switch[target,
			"Mean",
			(i++; RegisterData[{N[Mean@data[[#]]],maskRight[[#]],vox},{data[[#]],maskRight[[#]],vox},
				OutputTransformation->False, PrintTempDirectory->False, TempDirectory->tempDir, FilterRules[{opts},Options[RegisterData]]])&/@slices,
			"Median",
			(i++; RegisterData[{N[Median@data[[#]]],maskRight[[#]],vox},{data[[#]],maskRight[[#]],vox},
				OutputTransformation->False, PrintTempDirectory->False, TempDirectory->tempDir, FilterRules[{opts},Options[RegisterData]]])&/@slices,
			"First",
			(i++; RegisterData[{data[[#,1]],maskRight[[#]],vox},{data[[#]],maskRight[[#]],vox},
				OutputTransformation->False, PrintTempDirectory->False, TempDirectory->tempDir, FilterRules[{opts},Options[RegisterData]]])&/@slices,
			"stack",
			(i++; RegisterData[{data[[#]],ConstantArray[maskRight[[#]],size],vox},
				OutputTransformation->False, PrintTempDirectory->False, TempDirectory->tempDir, FilterRules[{opts},Options[RegisterData]]])&/@slices
		]
		,ProgressIndicator[i, {0,Length[data]}]
	];

	dataRight
]


(* ::Section:: *)
(*End Package*)


End[]

EndPackage[]

